MOUSEKEY_ENABLE     = yes     # Mouse keys
RGBLIGHT_ENABLE     = yes    # Enable WS2812 RGB underlight.
VIA_ENABLE      = yes    # Enable VIA
OLED_ENABLE     = no
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball
SRC += quantum/color.c
